/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyBarkRouteImport } from './routes/daily-bark'
import { Route as DigitalCollarRouteImport } from './routes/digital-collar'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FounderAccessRouteImport } from './routes/founder-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MunchieMenuRouteImport } from './routes/munchie-menu'
import { Route as NeighbourhoodWatchRouteImport } from './routes/neighbourhood-watch'
import { Route as PackSocialRouteImport } from './routes/pack-social'
import { Route as ProPortalRouteImport } from './routes/pro-portal'
import { Route as ProSignupRouteImport } from './routes/pro-signup'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyBarkRoute = DailyBarkRouteImport.update({
  id: '/daily-bark',
  path: '/daily-bark',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalCollarRoute = DigitalCollarRouteImport.update({
  id: '/digital-collar',
  path: '/digital-collar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderAccessRoute = FounderAccessRouteImport.update({
  id: '/founder-access',
  path: '/founder-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MunchieMenuRoute = MunchieMenuRouteImport.update({
  id: '/munchie-menu',
  path: '/munchie-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighbourhoodWatchRoute = NeighbourhoodWatchRouteImport.update({
  id: '/neighbourhood-watch',
  path: '/neighbourhood-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const PackSocialRoute = PackSocialRouteImport.update({
  id: '/pack-social',
  path: '/pack-social',
  getParentRoute: () => rootRouteImport,
} as any)
const ProPortalRoute = ProPortalRouteImport.update({
  id: '/pro-portal',
  path: '/pro-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProSignupRoute = ProSignupRouteImport.update({
  id: '/pro-signup',
  path: '/pro-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-bark': typeof DailyBarkRoute
  '/digital-collar': typeof DigitalCollarRoute
  '/emergency': typeof EmergencyRoute
  '/founder': typeof FounderRoute
  '/founder-access': typeof FounderAccessRoute
  '/login': typeof LoginRoute
  '/munchie-menu': typeof MunchieMenuRoute
  '/neighbourhood-watch': typeof NeighbourhoodWatchRoute
  '/pack-social': typeof PackSocialRoute
  '/pro-portal': typeof ProPortalRoute
  '/pro-signup': typeof ProSignupRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-bark': typeof DailyBarkRoute
  '/digital-collar': typeof DigitalCollarRoute
  '/emergency': typeof EmergencyRoute
  '/founder': typeof FounderRoute
  '/founder-access': typeof FounderAccessRoute
  '/login': typeof LoginRoute
  '/munchie-menu': typeof MunchieMenuRoute
  '/neighbourhood-watch': typeof NeighbourhoodWatchRoute
  '/pack-social': typeof PackSocialRoute
  '/pro-portal': typeof ProPortalRoute
  '/pro-signup': typeof ProSignupRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-bark': typeof DailyBarkRoute
  '/digital-collar': typeof DigitalCollarRoute
  '/emergency': typeof EmergencyRoute
  '/founder': typeof FounderRoute
  '/founder-access': typeof FounderAccessRoute
  '/login': typeof LoginRoute
  '/munchie-menu': typeof MunchieMenuRoute
  '/neighbourhood-watch': typeof NeighbourhoodWatchRoute
  '/pack-social': typeof PackSocialRoute
  '/pro-portal': typeof ProPortalRoute
  '/pro-signup': typeof ProSignupRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-bark'
    | '/digital-collar'
    | '/emergency'
    | '/founder'
    | '/founder-access'
    | '/login'
    | '/munchie-menu'
    | '/neighbourhood-watch'
    | '/pack-social'
    | '/pro-portal'
    | '/pro-signup'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily-bark'
    | '/digital-collar'
    | '/emergency'
    | '/founder'
    | '/founder-access'
    | '/login'
    | '/munchie-menu'
    | '/neighbourhood-watch'
    | '/pack-social'
    | '/pro-portal'
    | '/pro-signup'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/daily-bark'
    | '/digital-collar'
    | '/emergency'
    | '/founder'
    | '/founder-access'
    | '/login'
    | '/munchie-menu'
    | '/neighbourhood-watch'
    | '/pack-social'
    | '/pro-portal'
    | '/pro-signup'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyBarkRoute: typeof DailyBarkRoute
  DigitalCollarRoute: typeof DigitalCollarRoute
  EmergencyRoute: typeof EmergencyRoute
  FounderRoute: typeof FounderRoute
  FounderAccessRoute: typeof FounderAccessRoute
  LoginRoute: typeof LoginRoute
  MunchieMenuRoute: typeof MunchieMenuRoute
  NeighbourhoodWatchRoute: typeof NeighbourhoodWatchRoute
  PackSocialRoute: typeof PackSocialRoute
  ProPortalRoute: typeof ProPortalRoute
  ProSignupRoute: typeof ProSignupRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-bark': {
      id: '/daily-bark'
      path: '/daily-bark'
      fullPath: '/daily-bark'
      preLoaderRoute: typeof DailyBarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-collar': {
      id: '/digital-collar'
      path: '/digital-collar'
      fullPath: '/digital-collar'
      preLoaderRoute: typeof DigitalCollarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-access': {
      id: '/founder-access'
      path: '/founder-access'
      fullPath: '/founder-access'
      preLoaderRoute: typeof FounderAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/munchie-menu': {
      id: '/munchie-menu'
      path: '/munchie-menu'
      fullPath: '/munchie-menu'
      preLoaderRoute: typeof MunchieMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighbourhood-watch': {
      id: '/neighbourhood-watch'
      path: '/neighbourhood-watch'
      fullPath: '/neighbourhood-watch'
      preLoaderRoute: typeof NeighbourhoodWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack-social': {
      id: '/pack-social'
      path: '/pack-social'
      fullPath: '/pack-social'
      preLoaderRoute: typeof PackSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-portal': {
      id: '/pro-portal'
      path: '/pro-portal'
      fullPath: '/pro-portal'
      preLoaderRoute: typeof ProPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-signup': {
      id: '/pro-signup'
      path: '/pro-signup'
      fullPath: '/pro-signup'
      preLoaderRoute: typeof ProSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyBarkRoute: DailyBarkRoute,
  DigitalCollarRoute: DigitalCollarRoute,
  EmergencyRoute: EmergencyRoute,
  FounderRoute: FounderRoute,
  FounderAccessRoute: FounderAccessRoute,
  LoginRoute: LoginRoute,
  MunchieMenuRoute: MunchieMenuRoute,
  NeighbourhoodWatchRoute: NeighbourhoodWatchRoute,
  PackSocialRoute: PackSocialRoute,
  ProPortalRoute: ProPortalRoute,
  ProSignupRoute: ProSignupRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
